version: "3"
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: helloworld
      MYSQL_DATABASE: bakcyl
  bakcyl:
    depends_on:
      - db
    build: .
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - WAIT_HOSTS=db:3306
      - DISPLAY=${DISPLAY}
  admin:
      image: adminer
      ports:
        - "8080:8080"
